---
- name: "SCORED | 17.1.1 | PATCH | L1 Ensure Audit Credential Validation is set to Success and Failure"
  win_audit_policy_system:
    subcategory: Credential Validation
    audit_type: success, failure
  when:
    - rule_17_1_1
  tags:
    - level1
    - level2
    - rule_17.1.1
    - patch

- name: "SCORED | 17.1.2 | PATCH | L1 Ensure 'Audit Kerberos Authentication Service' is set to 'Success and Failure' (DC Only)"
  win_audit_policy_system:
    subcategory: Kerberos Authentication Service
    audit_type: success, failure
  when: rule_17_1_2
  tags:
    - level1
    - level2
    - rule_17.1.2
    - patch

- name: "SCORED | 17.1.3 | PATCH | L1 Ensure 'Audit Kerberos Service Ticket Operations' is set to 'Success and Failure' (DC Only)"
  win_audit_policy_system:
    subcategory: Kerberos Service Ticket Operations
    audit_type: success, failure
  when: rule_17_1_3
  tags:
    - level1
    - level2
    - rule_17.1.3
    - patch

- name: "SCORED | 17.2.1 | PATCH | L1 Ensure Audit Application Group Management is set to Success and Failure"
  win_audit_policy_system:
    subcategory: Application Group Management
    audit_type: success, failure
  when:
    - rule_17_2_1
  tags:
    - level1
    - level2
    - rule_17.2.1
    - patch

- name: "SCORED | 17.2.2 | PATCH | L1 Ensure Audit Computer Account Management is set to include Success DC only"
  win_audit_policy_system:
    subcategory: Computer Account Management
    audit_type: success
  when:
    - rule_17_2_2
  tags:
    - level1
    - level2
    - rule_17.2.2
    - patch

- name: "SCORED | 17.2.3 | AUDIT | L1 Ensure Audit Distribution Group Management is set to include Success DC only"
  win_audit_policy_system:
    subcategory: Distribution Group Management
    audit_type: success
  when:
    - rule_17_2_3
  tags:
    - level1
    - level2
    - rule_17.2.3
    - patch

- name: "SCORED | 17.2.4 | PATCH | L1 Ensure Audit Other Account Management Events is set to include Success DC only"
  win_audit_policy_system:
    subcategory: Other Account Management Events
    audit_type: success
  when:
    - rule_17_2_4
  tags:
    - level1
    - level2
    - rule_17.2.4
    - patch

- name: "SCORED | 17.2.5 | PATCH | L1 Ensure Audit Security Group Management is set to include Success"
  win_audit_policy_system:
    subcategory: Security Group Management
    audit_type: success
  when:
    - rule_17_2_5
  tags:
    - level1
    - level2
    - rule_17.2.5
    - patch

- name: "SCORED | 17.2.6 | AUDIT | L1 Ensure Audit User Account Management is set to Success and Failure"
  win_audit_policy_system:
    subcategory: User Account Management
    audit_type: success, failure
  when:
    - rule_17_2_6
  tags:
    - level1
    - level2
    - rule_17.2.6
    - patch

- name: "SCORED | 17.3.1 | PATCH | L1 Ensure Audit PNP Activity is set to include Success"
  win_audit_policy_system:
    subcategory: Plug and Play Events
    audit_type: success
  when:
    - rule_17_3_1
  tags:
    - level1
    - level2
    - rule_17.3.1
    - patch

- name: "SCORED | 17.3.2 | PATCH | L1 Ensure Audit Process Creation is set to include Success"
  win_audit_policy_system:
    subcategory: Process Creation
    audit_type: success
  when:
    - rule_17_3_2
  tags:
    - level1
    - level2
    - rule_17.3.2
    - patch

- name: "SCORED | 17.4.1 | PATCH | L1 Ensure Audit Directory Service Access is set to include Failure DC only"
  win_audit_policy_system:
    subcategory: Directory Service Access
    audit_type: failure
  when:
    - rule_17_4_1
  tags:
    - level1
    - level2
    - rule_17.4.1
    - patch

- name: "SCORED | 17.4.2 | PATCH | L1 Ensure Audit Directory Service Changes is set to include Success DC only"
  win_audit_policy_system:
    subcategory: Directory Service Changes
    audit_type: success
  when:
    - rule_17_4_2
  tags:
    - level1
    - level2
    - rule_17.4.2
    - patch

- name: "SCORED | 17.5.1 | PATCH | L1 Ensure Audit Account Lockout is set to include Failure"
  win_audit_policy_system:
    subcategory: Account Lockout
    audit_type: failure
  when:
    - rule_17_5_1
  tags:
    - level1
    - level2
    - rule_17.5.1
    - patch

- name: "SCORED | 17.5.2 | PATCH | L1 Ensure Audit Group Membership is set to include Success"
  win_audit_policy_system:
    subcategory: Group Membership
    audit_type: success
  when:
    - rule_17_5_2
  tags:
    - level1
    - level2
    - rule_17.5.2
    - patch

- name: "SCORED | 17.5.3 | PATCH | L1 Ensure Audit Logoff is set to include Success"
  win_audit_policy_system:
    subcategory: Logoff
    audit_type: success
  when:
    - rule_17_5_3
  tags:
    - level1
    - level2
    - rule_17.5.3
    - patch

- name: "SCORED | 17.5.4 | PATCH | L1 Ensure Audit Logon is set to Success and Failure | Failure"
  win_audit_policy_system:
    subcategory: Logon
    audit_type: success, failure
  when:
    - rule_17_5_4
  tags:
    - level1
    - level2
    - rule_17.5.4
    - patch

- name: "SCORED | 17.5.5 | PATCH | L1 Ensure Audit Other LogonLogoff Events is set to Success and Failure"
  win_audit_policy_system:
    subcategory: Other Logon/Logoff Events
    audit_type: success, failure
  when:
    - rule_17_5_5
  tags:
    - level1
    - level2
    - rule_17.5.5
    - patch

- name: "SCORED | 17.5.6 | PATCH | L1 Ensure Audit Special Logon is set to include Success"
  win_audit_policy_system:
    subcategory: Special Logon
    audit_type: success
  when:
    - rule_17_5_6
  tags:
    - level1
    - level2
    - rule_17.5.6
    - patch

- name: "SCORED | 17.6.1 | PATCH | L1 Ensure Audit Detailed File Share is set to include Failure"
  win_audit_policy_system:
    subcategory: Detailed File Share
    audit_type: failure
  when:
    - rule_17_6_1
  tags:
    - level1
    - level2
    - rule_17.6.1
    - patch

- name: "SCORED | 17.6.2 | PATCH | L1 Ensure Audit File Share is set to Success and Failure"
  win_audit_policy_system:
    subcategory: File Share
    audit_type: success, failure
  when:
    - rule_17_6_2
  tags:
    - level1
    - level2
    - rule_17.6.2
    - patch

- name: "SCORED | 17.6.3 | PATCH | L1 Ensure Audit Other Object Access Events is set to Success and Failure"
  win_audit_policy_system:
    subcategory: Other Object Access Events
    audit_type: success, failure
  when: rule_17_6_3
  tags:
    - level1
    - level2
    - rule_17.6.3
    - patch

- name: "SCORED | 17.6.4 | PATCH | L1 Ensure Audit Removable Storage is set to Success and Failure"
  win_audit_policy_system:
    subcategory: Removable Storage
    audit_type: success, failure
  when: rule_17_6_4
  tags:
    - level1
    - level2
    - rule_17.6.4
    - patch

- name: "SCORED | 17.7.1 | PATCH | L1 Ensure Audit Audit Policy Change is set to include Success"
  win_audit_policy_system:
    subcategory: Audit Policy Change
    audit_type: success
  when: rule_17_7_1
  tags:
    - level1
    - level2
    - rule_17.7.1
    - patch

- name: "SCORED | 17.7.2 | PATCH | L1 Ensure Audit Authentication Policy Change is set to include Success"
  win_audit_policy_system:
    subcategory: Authentication Policy Change
    audit_type: success
  when: rule_17_7_2
  tags:
    - level1
    - level2
    - rule_17.7.2
    - patch

- name: "SCORED | 17.7.3 | PATCH | L1 Ensure Audit Authorization Policy Change is set to include Success"
  win_audit_policy_system:
    subcategory: Authorization Policy Change
    audit_type: success
  when: rule_17_7_3
  tags:
    - level1
    - level2
    - rule_17.7.3
    - patch

- name: "SCORED | 17.7.4 | PATCH | L1 Ensure Audit MPSSVC Rule-Level Policy Change is set to Success and Failure"
  win_audit_policy_system:
    subcategory: MPSSVC Rule-Level Policy Change
    audit_type: success, failure
  when: rule_17_7_4
  tags:
    - level1
    - level2
    - rule_17.7.4
    - patch

- name: "SCORED | 17.7.5 | PATCH | L1 Ensure Audit Other Policy Change Events is set to include Failure"
  win_audit_policy_system:
    subcategory: Other Policy Change Events
    audit_type: failure
  when: rule_17_7_5
  tags:
    - level1
    - level2
    - rule_17.7.5
    - patch

- name: "SCORED | 17.8.1 | PATCH | L1 Ensure Audit Sensitive Privilege Use is set to Success and Failure"
  win_audit_policy_system:
    subcategory: Sensitive Privilege Use
    audit_type: success, failure
  when:
    - rule_17_8_1
  tags:
    - level1
    - level2
    - rule_17.8.1
    - patch

- name: "SCORED | 17.9.1 | PATCH | L1 Ensure Audit IPsec Driver is set to Success and Failure"
  win_audit_policy_system:
    subcategory: IPsec Driver
    audit_type: success, failure
  when:
    - rule_17_9_1
  tags:
    - level1
    - level2
    - rule_17.9.1
    - patch

- name: "SCORED | 17.9.2 | PATCH | L1 Ensure Audit Other System Events is set to Success and Failure"
  win_audit_policy_system:
    subcategory: Other System Events
    audit_type: success, failure
  when:
    - rule_17_9_2
  tags:
    - level1
    - level2
    - rule_17.9.2
    - patch

- name: "SCORED | 17.9.3 | PATCH | L1 Ensure Audit Security State Change is set to include Success"
  win_audit_policy_system:
    subcategory: Security State Change
    audit_type: success
  when: rule_17_9_3
  tags:
    - level1
    - level2
    - rule_17.9.3
    - patch

- name: "SCORED | 17.9.4 | PATCH | L1 Ensure Audit Security System Extension is set to include Success"
  win_audit_policy_system:
    subcategory: Security System Extension
    audit_type: success
  when: rule_17_9_4
  tags:
    - level1
    - level2
    - rule_17.9.4
    - patch

- name: "SCORED | 17.9.5 | PATCH | L1 Ensure Audit System Integrity is set to Success and Failure"
  win_audit_policy_system:
    subcategory: System Integrity
    audit_type: success, failure
  when:
    - rule_17_9_5
  tags:
    - level1
    - level2
    - rule_17.9.5
    - patch
